In [1]:
import os
import sys
from pathlib import Path

# Ajusta al root del repo Bluegrey si hace falta
ROOT = Path.cwd()
if (ROOT / "tools").exists():
    repo_root = ROOT
else:
    # si estás dentro de research/, sube un nivel
    repo_root = ROOT.parent

sys.path.append(str(repo_root))
print("Repo root:", repo_root)

Repo root: /Users/marina/Documents/jordi/projects/Trading/bluegrey/0. Discover/Bluegrey

In [2]:
from src.backtest.event_backtester import BacktestEngine
from strategies.base import BaseStrategy, StrategySignal
import src.infra.config as config
import pandas as pd

In [3]:
class DummyHoldStrategy(BaseStrategy):
    def on_bar(self, latest_bars):
        s = StrategySignal(signal_type="NONE")
        # ejemplo: no operar (solo para validar que el engine corre)
        return s

In [4]:
config.INSTRUMENTS

{'C:EURUSD': Forex('EURUSD', exchange='IDEALPRO'),
 'C:GBPUSD': Forex('GBPUSD', exchange='IDEALPRO'),
 'C:AUDUSD': Forex('AUDUSD', exchange='IDEALPRO'),
 'C:NZDUSD': Forex('NZDUSD', exchange='IDEALPRO'),
 'C:USDJPY': Forex('USDJPY', exchange='IDEALPRO')}

In [5]:
engine = BacktestEngine(
    strategy_class=DummyHoldStrategy,
    instruments=config.INSTRUMENTS,       # universo definido en config
    params={},
    data_library=config.LIBS["fx_min"],   # "fx.min"
    start_cap=100000
)

eq = engine.run(start_date="2024-01-01", end_date="2024-03-01")
eq.tail()

🗄️ Connected to ArcticDB at: lmdb:///Users/marina/Documents/jordi/projects/Trading/bluegrey/0. Discover/Bluegrey/data/arctic_db?map_size=10GB

⏳ Loading Data for 5 assets (2024-01-01 to 2024-03-01)...
▶️ Simulating 61283 ticks...
✅ Backtest Complete.

📊 --- QUICK RESULTS ---
   Initial Cap: $100,000.00
   Final Equity: $100,000.00
   Net PnL: $0.00 (0.00%)
   Total Trades: 0
-------------------------

📈 Generating Institutional Tearsheet (quantstats)...
⚠️ Returns volatility is zero (no active trades). Skipping Tearsheet.

                     equity
time
2024-02-29 23:56:00  100000
2024-02-29 23:57:00  100000
2024-02-29 23:58:00  100000
2024-02-29 23:59:00  100000
2024-03-01 00:00:00  100000

Empty DataFrame
Columns: []
Index: []