# Visualise data from ArcticDB

Run these cells from the Bluegrey repo with the `bluegrey` conda environment active.

Import ArcticDB. Import Path and sys to be able to find src/config.py and import the settings there.

In [ ]:
# --- import ArcticDB module for client setup ---
from arcticdb import Arctic

# --- Modules to manage directories and paths ---
from pathlib import Path # -- for handling filesystem paths
import sys # -- for managing the Python path to ensure project modules can be imported

# --- Ensure repo root is on sys.path so that src/config.py can be imported ---
ROOT_DIR = Path.cwd()

while not (ROOT_DIR / "src").exists(): # -- traverse up the directory tree until we find a directory containing 'src/'
    if ROOT_DIR.parent == ROOT_DIR: # -- if we reach the root of the filesystem without finding 'src/', raise an error and exit to avoid infinite loop
        raise RuntimeError("Could not find repo root containing 'src/'")
    ROOT_DIR = ROOT_DIR.parent

if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR)) # -- add repo root to sys.path at the start (to be read first) for module imports

# --- Now safe to import project config ---
import src.config as config

Connect to the ArcticDB database.

In [2]:
store = Arctic(config.ARCTIC_PATH)  # -- connect to ArcticDB store using path from config.

# If you run this line more than once you'll get a warning that the store is already initialized. You can ignore that if you're just running this notebook multiple times.

## --- Set the market & ticker frequency ---

In [ ]:
# What market do you want to see? i.e. "fx", "equity", "crypto", "options", "indices".
market = "crypto"

# What frequency do you want to see? i.e. "sec", "min", "hour", "day", "week", "month", "quarter", "year".
freq = "hour"

Build the library name from asset type and frequency.
<br>
Load the corresponding dataset from the config.

In [4]:
# Combine to get the library name, e.g. "fx_min"Arctic
lib_name = f"{market}_{freq}"

lib = store[config.LIBS[lib_name]]  # -- access the specific library for minute-level FX data as defined in config

See what symbols are in the library

In [5]:
symbols = sorted(lib.list_symbols()) # -- get sorted list of all symbols in the library
print(symbols)

# # Uncomment the following to see the symbols as an array
# import numpy as np
# np.array(symbols)

['X:00USD', 'X:1INCHUSD', 'X:A8USD', 'X:AAVEUSD', 'X:ABTUSD', 'X:ACAUSD', 'X:ACHUSD', 'X:ACSUSD', 'X:ACXUSD', 'X:ADAUSD', 'X:ADXUSD', 'X:AERGOUSD', 'X:AEROUSD', 'X:AEVOUSD', 'X:AGLDUSD', 'X:AIOZUSD', 'X:AIRUSD', 'X:AKTEUR', 'X:AKTUSD', 'X:ALBTUSD', 'X:ALCXUSD', 'X:ALEOUSD', 'X:ALEPHUSD', 'X:ALGOUSD', 'X:ALGUSD', 'X:ALICEUSD', 'X:ALPHAUSD', 'X:ALT2612USD', 'X:ALTUSD', 'X:AMPUSD', 'X:ANKRUSD', 'X:ANTUSD', 'X:APENFTUSD', 'X:APEUSD', 'X:API3USD', 'X:APTUSD', 'X:APUUSD', 'X:ARBUSD', 'X:ARKMUSD', 'X:ARPAUSD', 'X:ASMUSD', 'X:ASTRUSD', 'X:ASTUSD', 'X:ATAUSD', 'X:ATHUSD', 'X:ATLASUSD', 'X:ATOMUSD', 'X:ATOUSD', 'X:AUCTIONUSD', 'X:AUDIOUSD', 'X:AURORAUSD', 'X:AUSDTUSD', 'X:AVAXUSD', 'X:AVTUSD', 'X:AXLUSD', 'X:AXSUSD', 'X:AZEROUSD', 'X:B2MUSD', 'X:BADGERUSD', 'X:BALUSD', 'X:BANDUSD', 'X:BATUSD', 'X:BCHEUR', 'X:BCHGBP', 'X:BCHNUSD', 'X:BCHUSD', 'X:BEAMUSD', 'X:BESTUSD', 'X:BFTUSD', 'X:BGBUSD', 'X:BICOUSD', 'X:BIGTIMEUSD', 'X:BITUSD', 'X:BLASTUSD', 'X:BLURUSD', 'X:BLZUSD', 'X:BNBUSD', 'X:BNCUSD', 'X:BNTUSD', 'X:BOBAUSD', 'X:BODENUSD', 'X:BONDUSD', 'X:BONKEUR', 'X:BONKUSD', 'X:BORGUSD', 'X:BOSONUSD', 'X:BRICKUSD', 'X:BSVUSD', 'X:BSXUSD', 'X:BTCAUD', 'X:BTCEUR', 'X:BTCGBP', 'X:BTCJPY', 'X:BTCPYUSD', 'X:BTCUSD', 'X:BTGUSD', 'X:BTRSTUSD', 'X:BTSEUSD', 'X:BTTUSD', 'X:BUSDUSD', 'X:BXNUSD', 'X:C98USD', 'X:CBETHUSD', 'X:CCDUSD', 'X:CCUSD', 'X:CELOUSD', 'X:CELRUSD', 'X:CELUSD', 'X:CFGUSD', 'X:CGLDUSD', 'X:CHEXUSD', 'X:CHREUR', 'X:CHRUSD', 'X:CHSBUSD', 'X:CHZUSD', 'X:CLOUDUSD', 'X:CLOUSD', 'X:CLVUSD', 'X:CNHTUSD', 'X:COMPUSD', 'X:COQUSD', 'X:CORECHAINUSD', 'X:COTIUSD', 'X:COVALUSD', 'X:COWUSD', 'X:CPOOLUSD', 'X:CQTUSD', 'X:CROUSD', 'X:CRPTUSD', 'X:CRVUSD', 'X:CSMUSD', 'X:CSPRUSD', 'X:CTSIUSD', 'X:CTXUSD', 'X:CVCUSD', 'X:CVXUSD', 'X:CXTUSD', 'X:DAIUSD', 'X:DARUSD', 'X:DASHUSD', 'X:DBRUSD', 'X:DDXUSD', 'X:DEGENUSD', 'X:DENTUSD', 'X:DESOUSD', 'X:DEXTUSD', 'X:DGBUSD', 'X:DIAEUR', 'X:DIAUSD', 'X:DIMOUSD', 'X:DNTUSD', 'X:DOGEUSD', 'X:DOPUSD', 'X:DORAUSD', 'X:DOTUSD', 'X:DREPUSD', 'X:DRIFTUSD', 'X:DRVUSD', 'X:DSHUSD', 'X:DUSKUSD', 'X:DVFUSD', 'X:DYDXEUR', 'X:DYDXUSD', 'X:DYMUSD', 'X:DYPUSD', 'X:EDOUSD', 'X:EGLDUSD', 'X:EIGENUSD', 'X:ELAUSD', 'X:ENAUSD', 'X:ENJUSD', 'X:ENSUSD', 'X:EOSUSD', 'X:ERNUSD', 'X:ETCUSD', 'X:ETH2XUSD', 'X:ETHAUD', 'X:ETHBTC', 'X:ETHFIUSD', 'X:ETHPYUSD', 'X:ETHUSD', 'X:ETHWUSD', 'X:ETPUSD', 'X:EULUSD', 'X:EURCUSD', 'X:EURQUSD', 'X:EURRUSD', 'X:EURTUSD', 'X:EUTUSD', 'X:EWTUSD', 'X:FARMUSD', 'X:FCLUSD', 'X:FETUSD', 'X:FIDAUSD', 'X:FILUSD', 'X:FISUSD', 'X:FLOKIUSD', 'X:FLOWUSD', 'X:FLRUSD', 'X:FORTHUSD', 'X:FORTUSD', 'X:FOXUSD', 'X:FTMUSD', 'X:FTTUSD', 'X:FUNUSD', 'X:FWOGUSD', 'X:FXSUSD', 'X:FXUSD', 'X:GALAUSD', 'X:GALUSD', 'X:GARIUSD', 'X:GFIUSD', 'X:GHSTUSD', 'X:GIGAUSD', 'X:GLMRUSD', 'X:GLMUSD', 'X:GMMTUSD', 'X:GMTUSD', 'X:GMXUSD', 'X:GNOUSD', 'X:GNTUSD', 'X:GOATUSD', 'X:GODSUSD', 'X:GOMININGUSD', 'X:GRTUSD', 'X:GSTUSD', 'X:GTCUSD', 'X:GTXUSD', 'X:GUSD', 'X:GUSDUSD', 'X:GYENUSD', 'X:HBARUSD', 'X:HDXUSD', 'X:HFTUSD', 'X:HIGHUSD', 'X:HIXUSD', 'X:HMSTRUSD', 'X:HMTUSD', 'X:HNTUSD', 'X:HONEYUSD', 'X:HOPRUSD', 'X:HTXDAOUSD', 'X:HYPEUSD', 'X:ICEUSD', 'X:ICPUSD', 'X:ICXUSD', 'X:IDEXUSD', 'X:ILVUSD', 'X:IMXUSD', 'X:INDEXUSD', 'X:INJUSD', 'X:INTRUSD', 'X:INVUSD', 'X:IOTUSD', 'X:IOTXUSD', 'X:IOUSD', 'X:JASMYUSD', 'X:JSTUSD', 'X:JTOUSD', 'X:JUNOUSD', 'X:JUPUSD', 'X:JUSTICEUSD', 'X:JXXUSD', 'X:KANUSD', 'X:KARATEUSD', 'X:KARRATUSD', 'X:KARUSD', 'X:KASUSD', 'X:KAVAUSD', 'X:KEEPUSD', 'X:KEYUSD', 'X:KILTUSD', 'X:KINTUSD', 'X:KINUSD', 'X:KMNOUSD', 'X:KNCUSD', 'X:KP3RUSD', 'X:KRLUSD', 'X:KSMUSD', 'X:KUJIUSD', 'X:L3USD', 'X:LCXUSD', 'X:LDOUSD', 'X:LEOUSD', 'X:LIFIIIUSD', 'X:LINKUSD', 'X:LITUSD', 'X:LMWRUSD', 'X:LOCKINUSD', 'X:LOKAUSD', 'X:LPTUSD', 'X:LQTYUSD', 'X:LRCUSD', 'X:LRDSUSD', 'X:LSETHUSD', 'X:LSKUSD', 'X:LTCAUD', 'X:LTCBTC', 'X:LTCEUR', 'X:LTCUSD', 'X:LUNA2USD', 'X:LUNAUSD', 'X:LYMUSD', 'X:MAGICUSD', 'X:MANAUSD', 'X:MANEKIUSD', 'X:MASKUSD', 'X:MATHUSD', 'X:MATICUSD', 'X:MCO2USD', 'X:MCUSD', 'X:MDTUSD', 'X:MEDIAUSD', 'X:MELANIAUSD', 'X:MEMEUSD', 'X:METISUSD', 'X:MEUSD', 'X:MEWUSD', 'X:MICHIUSD', 'X:MIMUSD', 'X:MINAUSD', 'X:MIRUSD', 'X:MKRUSD', 'X:MLNUSD', 'X:MNAUSD', 'X:MNDEUSD', 'X:MNGOUSD', 'X:MNTUSD', 'X:MOBILEUSD', 'X:MOBUSD', 'X:MODEUSD', 'X:MOGUSD', 'X:MONAUSD', 'X:MOODENGUSD', 'X:MOONUSD', 'X:MORPHOUSD', 'X:MOVEUSD', 'X:MOVRUSD', 'X:MPCUSD', 'X:MPLUSD', 'X:MSOLUSD', 'X:MTLUSD', 'X:MULTIUSD', 'X:MUSDUSD', 'X:MUSEUSD', 'X:MVUSD', 'X:MXCUSD', 'X:MXNTUSD', 'X:NANOUSD', 'X:NCTUSD', 'X:NEARUSD', 'X:NEIROUSD', 'X:NEONUSD', 'X:NEOUSD', 'X:NESTUSD', 'X:NEXOUSD', 'X:NKNUSD', 'X:NMRUSD', 'X:NODLUSD', 'X:NOSUSD', 'X:NOTUSD', 'X:NTRNUSD', 'X:NUUSD', 'X:NXRAUSD', 'X:NYMUSD', 'X:OCEANUSD', 'X:OGNUSD', 'X:OMGUSD', 'X:OMNIUSD', 'X:OMNUSD', 'X:ONDOUSD', 'X:OOKIUSD', 'X:OPUSD', 'X:OPXUSD', 'X:ORCAEUR', 'X:ORCAUSD', 'X:ORNUSD', 'X:OSMOUSD', 'X:OXTUSD', 'X:OXYUSD', 'X:PASUSD', 'X:PAXGUSD', 'X:PAXUSD', 'X:PDAUSD', 'X:PENDLEUSD', 'X:PEPEUSD', 'X:PERPUSD', 'X:PHAUSD', 'X:PIRATEUSD', 'X:PLANETSUSD', 'X:PLAUSD', 'X:PLUUSD', 'X:PNGUSD', 'X:PNKUSD', 'X:PNUTUSD', 'X:POLISUSD', 'X:POLSUSD', 'X:POLUSD', 'X:POLYUSD', 'X:PONDUSD', 'X:PONKEUSD', 'X:POPCATUSD', 'X:PORTALUSD', 'X:POWRUSD', 'X:PRCLUSD', 'X:PRIMEUSD', 'X:PROUSD', 'X:PRQUSD', 'X:PSTAKEUSD', 'X:PUFFERUSD', 'X:PUNDIXUSD', 'X:PYRUSD', 'X:PYTHUSD', 'X:PYUSDUSD', 'X:QIUSD', 'X:QNTUSD', 'X:QRDOUSD', 'X:QSPUSD', 'X:QTFUSD', 'X:QTMUSD', 'X:QTUMUSD', 'X:QUICKUSD', 'X:RADUSD', 'X:RAIUSD', 'X:RAREUSD', 'X:RARIEUR', 'X:RARIUSD', 'X:RAYUSD', 'X:RBCUSD', 'X:RBNUSD', 'X:REEFUSD', 'X:RENDERUSD', 'X:RENUSD', 'X:REPUSD', 'X:REPV2USD', 'X:REQUSD', 'X:REZUSD', 'X:RGTUSD', 'X:RLCUSD', 'X:RLUSDUSD', 'X:RLYUSD', 'X:RNDRUSD', 'X:RONINUSD', 'X:ROOKUSD', 'X:ROSEUSD', 'X:RPLUSD', 'X:RRTUSD', 'X:RSRUSD', 'X:RUNEUSD', 'X:SAFEUSD', 'X:SAGAUSD', 'X:SAMOUSD', 'X:SANDUSD', 'X:SBRUSD', 'X:SCROLLUSD', 'X:SCRTUSD', 'X:SCUSD', 'X:SDNUSD', 'X:SDUSD', 'X:SEAMUSD', 'X:SEIEUR', 'X:SEIUSD', 'X:SGBUSD', 'X:SHDWUSD', 'X:SHIBUSD', 'X:SHPINGUSD', 'X:SKLUSD', 'X:SKYUSD', 'X:SMTUSD', 'X:SNTUSD', 'X:SNXUSD', 'X:SOLUSD', 'X:SPAUSD', 'X:SPECUSD', 'X:SPELLUSD', 'X:SPXUSD', 'X:SRMUSD', 'X:STEPUSD', 'X:STGUSD', 'X:STORJUSD', 'X:STRDUSD', 'X:STRKEUR', 'X:STRKUSD', 'X:STXUSD', 'X:SUIUSD', 'X:SUKUUSD', 'X:SUNUSD', 'X:SUPERUSD', 'X:SUSHIUSD', 'X:SWEATUSD', 'X:SWELLUSD', 'X:SWFTCUSD', 'X:SYLOUSD', 'X:SYNUSD', 'X:SYRUPUSD', 'X:TAIKOUSD', 'X:TAOUSD', 'X:TBTCUSD', 'X:TEERUSD', 'X:THETAUSD', 'X:TIAUSD', 'X:TIMEUSD', 'X:TITAN1USD', 'X:TITAN2USD', 'X:TLMUSD', 'X:TLOSUSD', 'X:TNSRUSD', 'X:TOKENUSD', 'X:TOKEUSD', 'X:TOMIUSD', 'X:TONEUSD', 'X:TONUSD', 'X:TRACUSD', 'X:TRADEUSD', 'X:TRBUSD', 'X:TREMPUSD', 'X:TRIBEUSD', 'X:TRUMPUSD', 'X:TRUUSD', 'X:TRXUSD', 'X:TSDUSD', 'X:TURBOUSD', 'X:TUSD', 'X:TUSDEUR', 'X:TVKEUR', 'X:TVKUSD', 'X:UDCUSD', 'X:UMAUSD', 'X:UNFIUSD', 'X:UNIUSD', 'X:UOSUSD', 'X:UPIUSD', 'X:USDCUSD', 'X:USDGUSD', 'X:USDQUSD', 'X:USDRUSD', 'X:USDSUSD', 'X:USDTUSD', 'X:USTBLUSD', 'X:USTUSD', 'X:UTKUSD', 'X:UXLINKUSD', 'X:VANRYUSD', 'X:VARAUSD', 'X:VEEUSD', 'X:VELARUSD', 'X:VELOUSD', 'X:VETUSD', 'X:VGXUSD', 'X:VOXELUSD', 'X:VSYUSD', 'X:VTHOUSD', 'X:WAMPLUSD', 'X:WAVESUSD', 'X:WAXLUSD', 'X:WAXUSD', 'X:WBTCUSD', 'X:WBTUSD', 'X:WCFGUSD', 'X:WECANUSD', 'X:WELLUSD', 'X:WENUSD', 'X:WEUR', 'X:WHBTUSD', 'X:WIFEUR', 'X:WIFUSD', 'X:WILDUSD', 'X:WLUNAUSD', 'X:WNCGUSD', 'X:WOOUSD', 'X:WUSD', 'X:XAUTUSD', 'X:XCADUSD', 'X:XCNUSD', 'X:XDCUSD', 'X:XLMUSD', 'X:XMRUSD', 'X:XRAUSD', 'X:XRDUSD', 'X:XRPAUD', 'X:XRPBTC', 'X:XRPUSD', 'X:XRTUSD', 'X:XTPUSD', 'X:XTZUSD', 'X:XVGUSD', 'X:XYOUSD', 'X:YFIIUSD', 'X:YFIUSD', 'X:YGGEUR', 'X:YGGUSD', 'X:ZCNUSD', 'X:ZECUSD', 'X:ZENUSD', 'X:ZETACHAINUSD', 'X:ZETAUSD', 'X:ZEUSUSD', 'X:ZEXUSD', 'X:ZILUSD', 'X:ZKUSD', 'X:ZKXUSD', 'X:ZMTUSD', 'X:ZROUSD', 'X:ZRXUSD']

##  --- Set symbol ---

In [6]:
# Choose a symbol to visualize, e.g. "C:EURUSD", or "X:BTCUSD" for crypto. Make sure it exists in the library.
# symbol = "C:EURUSD" # -- example for FX
symbol = "X:BTCUSD" # -- example for crypto

Put the desired data from the Arctic database into a dataframe

In [7]:
# Fetch the data for the chosen symbol. This will return a DataFrame with columns like 'open', 'high', 'low', 'close', 'volume', etc.
df = lib.read(symbol).data
# df.head()
df

,open,high,low,close,volume,vwap
timestamp,,,,,,
2013-11-04 00:00:00,209.74800,211.47000,209.74800,211.30000,1.146469,210.7808
2013-11-04 01:00:00,211.64000,212.20000,211.64000,212.20000,1.218420,212.0926
2013-11-04 02:00:00,212.61825,212.81600,211.55854,211.55854,0.258348,212.6275
2013-11-04 03:00:00,211.54000,211.54000,209.97000,210.70852,0.958214,211.1656
2013-11-04 04:00:00,210.28920,210.70316,209.40010,210.70095,1.722571,209.6249
...,...,...,...,...,...,...
2026-04-08 19:00:00,71101.76000,71391.34000,70981.00000,71331.51000,672.535896,71261.1345
2026-04-08 20:00:00,71271.00000,71500.00000,71230.00000,71387.32000,354.546346,71396.8281
2026-04-08 21:00:00,71382.40000,71766.61000,71298.00000,71562.97000,556.036091,71593.5581
2026-04-08 22:00:00,71562.96000,71584.44000,71038.00000,71068.09000,338.937460,71296.3644
2026-04-08 23:00:00,71088.70000,71218.00000,70886.00000,71130.60000,351.379207,71039.9665

Review brief statistics of dataframe

In [8]:
# --- Read and display basic statistics for the FX data ---
print("Data Summary Statistics:")
print(df.describe())
print("\nData Info:")
print(df.info())

Data Summary Statistics:
                open          high            low          close  \
count   98707.000000   98707.00000   98707.000000   98707.000000
mean    28710.056451   28861.72535   28570.058640   28711.393725
std     32267.330637   32391.38895   32153.810372   32268.421542
min       175.000000     175.00000       0.060000     175.000000
25%      3837.075000    3924.59500    3782.240000    3814.325000
50%     11810.000000   11896.90000   11722.009408   11809.400000
75%     45651.665000   45956.34500   45319.695000   45648.390000
max    126099.210000  126296.00000  125210.000000  126099.220000

             volume           vwap
count  98707.000000   98707.000000
mean    1531.450085   28709.406297
std     2385.495054   32267.794289
min        0.000015     175.000000
25%      208.606800    3830.973850
50%      815.674125   11803.115300
75%     1948.943285   45661.260400
max    66073.019559  125695.431800

Data Info:
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 98707 entries, 2013-11-04 00:00:00 to 2026-04-08 23:00:00
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   open    98707 non-null  float64
 1   high    98707 non-null  float64
 2   low     98707 non-null  float64
 3   close   98707 non-null  float64
 4   volume  98707 non-null  float64
 5   vwap    98707 non-null  float64
dtypes: float64(6)
memory usage: 5.3 MB
None

Select a certain time-range of data to see

In [9]:
from pandas import to_datetime as to_datetime

initial_time = "2026-01-01"
final_time = "2026-02-01"
initial_final_range= (to_datetime(initial_time), to_datetime(final_time))

df_range = lib.read(
    symbol,
    date_range = initial_final_range
).data

# df_range.head()
df_range

,open,high,low,close,volume,vwap
timestamp,,,,,,
2026-01-01 00:00:00,87497.95,87930.0,87456.10,87650.01,296.245398,87604.5657
2026-01-01 01:00:00,87663.50,88117.0,87642.20,87796.09,256.801534,87788.5330
2026-01-01 02:00:00,87810.30,88156.0,87666.89,87753.11,306.893146,87837.5991
2026-01-01 03:00:00,87764.00,88074.0,87667.26,87696.53,167.924944,87770.3679
2026-01-01 04:00:00,87696.53,87907.0,87361.74,87418.55,803.006602,87481.7569
...,...,...,...,...,...,...
2026-01-31 20:00:00,77648.30,78171.0,76968.80,77889.11,1347.805084,77440.3263
2026-01-31 21:00:00,77896.00,78415.0,77268.78,78204.41,1130.764039,77889.4855
2026-01-31 22:00:00,78343.00,78556.0,77881.50,78060.69,845.580281,78138.6078
2026-01-31 23:00:00,78085.40,79279.0,77972.00,78648.00,1096.231276,78599.4306
2026-02-01 00:00:00,78648.40,79503.0,78552.70,78817.01,712.341611,78991.6536